//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dashboard.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardItem
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> BoardId { get; set; }
        public string Value { get; set; }
        public string AuthorId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> PositionX { get; set; }
        public Nullable<double> PositionY { get; set; }
        public Nullable<int> ZIndex { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual BoardItemType BoardItemType { get; set; }
    }
}
