//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dashboard.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class localDBEntities : DbContext
    {
        public localDBEntities()
            : base("name=localDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Doc> Doc { get; set; }
        public virtual DbSet<DocComment> DocComment { get; set; }
        public virtual DbSet<DocType> DocType { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupUsers> GroupUsers { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<Board> Board { get; set; }
        public virtual DbSet<BoardItem> BoardItem { get; set; }
        public virtual DbSet<BoardItemType> BoardItemType { get; set; }
        public virtual DbSet<BoardGroup> BoardGroup { get; set; }
    }
}
